<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Validations\**" />
    <Content Remove="Application\Validations\**" />
    <EmbeddedResource Remove="Application\Validations\**" />
    <None Remove="Application\Validations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />    
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />    
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR" Version="12.4.0" />   
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />   
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tekton.Products.Domain\Tekton.Products.Domain.csproj" />
    <ProjectReference Include="..\Tekton.Products.Infrastructure\Tekton.Products.Infrastructure.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties properties_4launchsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
